import numpy as np


def _getCmdBytes(value :str) -> bytes:
    return bytes([int(value, 16) >> 8 & 0xFF, int(value, 16) & 0xFF])


class GlobalVariableT24:
    ASIC_MODEL = "T24"
    RESOL = "UHD"
    nrow = 2160
    ncol = 30720
    LINE_LENGTH = 30720
    CB_LINE = 9
    APG_LINE = 24
    NUM_OF_VPARAM_LUT = 17

    POT_LOG_PRINT = True

    # POT Enviroment
    POT_IP = "192.168.0.7"                  # POT board IP 주소
    PC_IP = "192.168.0.1"                  # PC IP 주소
    OP_PORTNUM = 4000                       # 일반 PC 명령어에 사용하는 포트
    PL_PORTNUM = 5000                       # Phase Lock 설정에 사용하는 포트
    PL_SETTING = "LGD_POT_A05_F08"          # Phase Lock 설정에 사용하는 Packet 값
    PC_COMMAND_DELAY = 0.002                # PC Command Packet 전송과 전송사이 delay 설정값 (second)
    POT_CONNECT_DELAY = 0.1                 # POT 연결 시, PL setting, POT ready Packet 전송사이 delay 설정값 (second)
    PC_MODE_CLEAR_DELAY = 0.6               # PC Mode Clear 완료 후 delay 설정값 (second)

    # POT Packet - Header
    HEADER_WR_0BYTE = 0                     # Header Packet 중 Write Length Index 값이 0Byte mode임을 표시
    HEADER_WR_1LINE = 1                     # Header Packet 중 Write Length Index 값이 1라인 mode임을 표시
    # POT Packet - Footer
    FOOTER_SUCCESS = 0                      # Footer Packet 중 동작 성공 여부 표시
    FOOTER_CHECKSUM_ERROR2 = 3              # Footer Packet 즁 T-Con <--> NAND 통신 Checksum 실패 여부 표시
    FOOTER_SENSING_FAIL = 4                 # Footer Packet 중 Sensing 실패 여부 표시
    FOOTER_WR_0BYTE = 0                     # Footer Packet 중 Read Length Index 값이 0Byte mode임을 표시
    FOOTER_WR_1LINE = 1                     # Footer Packet 중 Read Length Index 값이 1라인 mode임을 표시
    # POT Packet - Ack
    ACK_FLAG = 250                          # ACK Packet 임을 표시
    ACK_SUCCESS = 0                         # ACK Packet 즁 동작 성공 여부 표시
    ACK_TIMEOUT_TCON = 1                    # ACK Packet 즁 T-Con에서 timeout 여부 표시
    ACK_CHECKSUM_ERROR1 = 2                 # ACK Packet 즁 POT <--> T-Con 통신 Checksum 실패 여부 표시
    ACK_CHECKSUM_ERROR2 = 3                 # ACK Packet 즁 T-Con <--> NAND 통신 Checksum 실패 여부 표시

    # PC Command
    CMD_TCON_RESET = _getCmdBytes("0x0040")
    CMD_POWER_RESET = None                # T26 추가
    CMD_SET_EMERGENCY = _getCmdBytes("0x1040")              # T22 추가
    CMD_CLR_EMERGENCY = _getCmdBytes("0x10C0")              # T22 추가
    CMD_SET_PCMODE = _getCmdBytes("0x2040")
    CMD_CLR_PCMODE = _getCmdBytes("0x20C0")
    CMD_RD_TCON_VPARAM = _getCmdBytes("0x3000")
    CMD_WR_TCON_VPARAM = _getCmdBytes("0x3020")
    CMD_RD_OPARAM = _getCmdBytes("0x3080")
    CMD_WR_OPARAM = _getCmdBytes("0x30A0")
    CMD_SEN_AVC = _getCmdBytes("0x4000")
    CMD_SEN_REF = _getCmdBytes("0x4080")
    CMD_SEN_SMODE_R = _getCmdBytes("0x5000")
    CMD_SEN_SMODE_W = _getCmdBytes("0x5008")
    CMD_SEN_SMODE_G = _getCmdBytes("0x5010")
    CMD_SEN_SMODE_B = _getCmdBytes("0x5018")
    CMD_SEN_FMODE_R = _getCmdBytes("0x5080")
    CMD_SEN_FMODE_W = _getCmdBytes("0x5088")
    CMD_SEN_FMODE_G = _getCmdBytes("0x5090")
    CMD_SEN_FMODE_B = _getCmdBytes("0x5098")
    CMD_SEN_SMODE_4C = _getCmdBytes("0x5180")               # T22 추가
    CMD_SEN_FMODE_4C = _getCmdBytes("0x5200")               # T22 추가
    CMD_SEN_AMODE_R = _getCmdBytes("0x5100")                # T22 추가
    CMD_SEN_AMODE_W = _getCmdBytes("0x5108")                # T22 추가
    CMD_SEN_AMODE_G = _getCmdBytes("0x5110")                # T22 추가
    CMD_SEN_AMODE_B = _getCmdBytes("0x5118")                # T22 추가
    CMD_SEN_ADPD5_R = _getCmdBytes("0x5280")                # T22 추가
    CMD_SEN_ADPD5_W = _getCmdBytes("0x5288")                # T22 추가
    CMD_SEN_ADPD5_G = _getCmdBytes("0x5290")                # T22 추가
    CMD_SEN_ADPD5_B = _getCmdBytes("0x5298")                # T22 추가
    CMD_SEN_ADPD5_4C = _getCmdBytes("0x5300")               # T22 추가
    CMD_SEN_OFFRF_MODE_R = None           # T26 추가
    CMD_SEN_OFFRF_MODE_W = None           # T26 추가
    CMD_SEN_OFFRF_MODE_G = None           # T26 추가
    CMD_SEN_OFFRF_MODE_B = None           # T26 추가
    CMD_SEN_OFFRF_MODE_4C = None          # T26 추가
    CMD_RD_NAND_SET_LPARAM = _getCmdBytes("0x7480")
    CMD_WR_NAND_SET_LPARAM = _getCmdBytes("0x74A0")
    CMD_ER_NAND_SET_LPARAM = _getCmdBytes("0x74C0")
    CMD_RD_NAND_LPARAM = _getCmdBytes("0x6080")
    CMD_WR_NAND_LPARAM = _getCmdBytes("0x60A0")
    CMD_ER_NAND_LPARAM = _getCmdBytes("0x60C0")
    CMD_RD_NAND_SET_VPARAM = _getCmdBytes("0x6100")
    CMD_WR_NAND_SET_VPARAM = _getCmdBytes("0x6120")
    CMD_ER_NAND_SET_VPARAM = _getCmdBytes("0x6140")
    CMD_RD_NAND_LGD_VPARAM = _getCmdBytes("0x6180")
    CMD_WR_NAND_LGD_VPARAM = _getCmdBytes("0x61A0")
    CMD_ER_NAND_LGD_VPARAM = _getCmdBytes("0x61C0")
    CMD_RD_NAND_RS1_FLAG = _getCmdBytes("0x6200")
    CMD_WR_NAND_RS1_FLAG = _getCmdBytes("0x6220")
    CMD_ER_NAND_RS1_FLAG = _getCmdBytes("0x6240")
    CMD_RD_NAND_RS2_FLAG = _getCmdBytes("0x6280")
    CMD_WR_NAND_RS2_FLAG = _getCmdBytes("0x62A0")
    CMD_ER_NAND_RS2_FLAG = _getCmdBytes("0x62C0")
    CMD_RD_NAND_YB_INFO1 = None           # T26 추가
    CMD_WR_NAND_YB_INFO1 = None           # T26 추가
    CMD_ER_NAND_YB_INFO1 = None           # T26 추가
    CMD_RD_NAND_YB_INFO2 = None           # T26 추가
    CMD_WR_NAND_YB_INFO2 = None           # T26 추가
    CMD_ER_NAND_YB_INFO2 = None           # T26 추가
    CMD_RD_NAND_BLC1 = _getCmdBytes("0x6500")
    CMD_WR_NAND_BLC1 = _getCmdBytes("0x6520")
    CMD_ER_NAND_BLC1 = _getCmdBytes("0x6540")
    CMD_RD_NAND_BLC2 = _getCmdBytes("0x6580")
    CMD_WR_NAND_BLC2 = _getCmdBytes("0x65A0")
    CMD_ER_NAND_BLC2 = _getCmdBytes("0x65C0")
    CMD_RD_NAND_CRP1_FLAG = _getCmdBytes("0x6600")
    CMD_WR_NAND_CRP1_FLAG = _getCmdBytes("0x6620")
    CMD_ER_NAND_CRP1_FLAG = _getCmdBytes("0x6640")
    CMD_RD_NAND_CRP2_FLAG = _getCmdBytes("0x6680")
    CMD_WR_NAND_CRP2_FLAG = _getCmdBytes("0x66A0")
    CMD_ER_NAND_CRP2_FLAG = _getCmdBytes("0x66C0")
    CMD_WR_NAND_CME_PHI1 = None
    CMD_RD_NAND_CME_PHI1 = None
    CMD_ER_NAND_CME_PHI1 = None
    CMD_WR_NAND_CME_PHI2 = None
    CMD_RD_NAND_CME_PHI2 = None
    CMD_ER_NAND_CME_PHI2 = None
    CMD_RD_NAND_CME_ALPHA1 = _getCmdBytes("0x6700")
    CMD_WR_NAND_CME_ALPHA1 = _getCmdBytes("0x6720")
    CMD_ER_NAND_CME_ALPHA1 = _getCmdBytes("0x6740")
    CMD_RD_NAND_CME_ALPHA2 = _getCmdBytes("0x6780")
    CMD_WR_NAND_CME_ALPHA2 = _getCmdBytes("0x67A0")
    CMD_ER_NAND_CME_ALPHA2 = _getCmdBytes("0x67C0")
    CMD_RD_NAND_ATCB = None               # T26 추가
    CMD_WR_NAND_ATCB = None               # T26 추가
    CMD_ER_NAND_ATCB = None               # T26 추가
    CMD_RD_NAND_GVC = None                # T26 추가
    CMD_WR_NAND_GVC = None                # T26 추가
    CMD_ER_NAND_GVC = None                # T26 추가
    CMD_RD_NAND_IPA_PHI = None            # T26 추가
    CMD_WR_NAND_IPA_PHI = None            # T26 추가
    CMD_ER_NAND_IPA_PHI = None            # T26 추가
    CMD_RD_NAND_PHI1 = None               # T26 추가
    CMD_WR_NAND_PHI1 = None               # T26 추가
    CMD_ER_NAND_PHI1 = None               # T26 추가
    CMD_RD_NAND_PHI2 = None               # T26 추가
    CMD_WR_NAND_PHI2 = None               # T26 추가
    CMD_ER_NAND_PHI2 = None               # T26 추가
    CMD_RD_NAND_PHI_YCB1 = None           # T26 추가
    CMD_WR_NAND_PHI_YCB1 = None           # T26 추가
    CMD_ER_NAND_PHI_YCB1 = None           # T26 추가
    CMD_RD_NAND_PHI_YCB2 = None           # T26 추가
    CMD_WR_NAND_PHI_YCB2 = None           # T26 추가
    CMD_ER_NAND_PHI_YCB2 = None           # T26 추가
    CMD_RD_NAND_ALPHA1 = None             # T26 추가
    CMD_WR_NAND_ALPHA1 = None             # T26 추가
    CMD_ER_NAND_ALPHA1 = None             # T26 추가
    CMD_RD_NAND_ALPHA2 = None             # T26 추가
    CMD_WR_NAND_ALPHA2 = None             # T26 추가
    CMD_ER_NAND_ALPHA2 = None             # T26 추가
    CMD_RD_NAND_IPA_ALPHA = None          # T26 추가
    CMD_WR_NAND_IPA_ALPHA = None          # T26 추가
    CMD_ER_NAND_IPA_ALPHA = None          # T26 추가
    CMD_RD_NAND_CB = _getCmdBytes("0x6B80")
    CMD_WR_NAND_CB = _getCmdBytes("0x6BA0")
    CMD_ER_NAND_CB = _getCmdBytes("0x6BC0")
    CMD_RD_NAND_APG = _getCmdBytes("0x6C00")
    CMD_WR_NAND_APG = _getCmdBytes("0x6C20")
    CMD_ER_NAND_APG = _getCmdBytes("0x6C40")
    CMD_RD_NAND_IPA = _getCmdBytes("0x6C80")
    CMD_WR_NAND_IPA = _getCmdBytes("0x6CA0")
    CMD_ER_NAND_IPA = _getCmdBytes("0x6CC0")
    CMD_RD_NAND_YB1 = _getCmdBytes("0x6D00")
    CMD_WR_NAND_YB1 = _getCmdBytes("0x6D20")
    CMD_ER_NAND_YB1 = _getCmdBytes("0x6D40")
    CMD_RD_NAND_YB2 = _getCmdBytes("0x6D80")
    CMD_WR_NAND_YB2 = _getCmdBytes("0x6DA0")
    CMD_ER_NAND_YB2 = _getCmdBytes("0x6DC0")
    CMD_RD_NAND_YB_YCB1 = _getCmdBytes("0x6E00")
    CMD_WR_NAND_YB_YCB1 = _getCmdBytes("0x6E20")
    CMD_ER_NAND_YB_YCB1 = _getCmdBytes("0x6E40")
    CMD_RD_NAND_YB_YCB2 = _getCmdBytes("0x6E80")
    CMD_WR_NAND_YB_YCB2 = _getCmdBytes("0x6EA0")
    CMD_ER_NAND_YB_YCB2 = _getCmdBytes("0x6EC0")
    CMD_RD_NAND_YCB = _getCmdBytes("0x6F00")
    CMD_WR_NAND_YCB = _getCmdBytes("0x6F20")
    CMD_ER_NAND_YCB = _getCmdBytes("0x6F40")
    CMD_RD_NAND_RT_REF = _getCmdBytes("0x6F80")
    CMD_WR_NAND_RT_REF = _getCmdBytes("0x6FA0")
    CMD_ER_NAND_RT_REF = _getCmdBytes("0x6FC0")
    CMD_RD_NAND_SET_PDCS_LUT1 = None
    CMD_WR_NAND_SET_PDCS_LUT1 = None
    CMD_ER_NAND_SET_PDCS_LUT1 = None
    CMD_RD_NAND_SET_PDCS_LUT2 = None
    CMD_WR_NAND_SET_PDCS_LUT2 = None
    CMD_ER_NAND_SET_PDCS_LUT2 = None
    CMD_RD_NAND_SET_PDCS_LUT1 = _getCmdBytes("0x7680")
    CMD_WR_NAND_SET_PDCS_LUT1 = _getCmdBytes("0x76A0")
    CMD_ER_NAND_SET_PDCS_LUT1 = _getCmdBytes("0x76C0")
    CMD_RD_NAND_SET_PDCS_LUT2 = _getCmdBytes("0x7700")
    CMD_WR_NAND_SET_PDCS_LUT2 = _getCmdBytes("0x7720")
    CMD_ER_NAND_SET_PDCS_LUT2 = _getCmdBytes("0x7740")
    CMD_RD_NAND_S_PARAM = _getCmdBytes("0x6000")
    CMD_WR_NAND_S_PARAM = _getCmdBytes("0x6020")
    CMD_ER_NAND_S_PARAM = _getCmdBytes("0x6040")
    CMD_RD_NAND_G_PARAM = _getCmdBytes("0x6900")
    CMD_WR_NAND_G_PARAM = _getCmdBytes("0x6920")
    CMD_ER_NAND_G_PARAM = _getCmdBytes("0x6940")
    CMD_RD_NAND_TIMER1 = _getCmdBytes("0x6980")
    CMD_WR_NAND_TIMER1 = _getCmdBytes("0x69A0")
    CMD_ER_NAND_TIMER1 = _getCmdBytes("0x69C0")
    CMD_RD_NAND_TIMER2 = _getCmdBytes("0x6A00")
    CMD_WR_NAND_TIMER2 = _getCmdBytes("0x6A20")
    CMD_ER_NAND_TIMER2 = _getCmdBytes("0x6A40")
    CMD_RD_NAND_TEMP1 = _getCmdBytes("0x6A80")
    CMD_WR_NAND_TEMP1 = _getCmdBytes("0x6AA0")
    CMD_ER_NAND_TEMP1 = _getCmdBytes("0x6AC0")
    CMD_RD_NAND_TEMP2 = _getCmdBytes("0x6B00")
    CMD_WR_NAND_TEMP2 = _getCmdBytes("0x6B20")
    CMD_ER_NAND_TEMP2 = _getCmdBytes("0x6B40")
    CMD_RD_NAND_OC1_1LINE = _getCmdBytes("0x7000")
    CMD_WR_NAND_OC1_1LINE = _getCmdBytes("0x7020")
    CMD_ER_NAND_OC1_1LINE = _getCmdBytes("0x7040")
    CMD_RD_NAND_OC1 = _getCmdBytes("0x7080")
    CMD_WR_NAND_OC1 = _getCmdBytes("0x70A0")
    CMD_ER_NAND_OC1 = _getCmdBytes("0x70C0")
    CMD_RD_NAND_OC2_1LINE = _getCmdBytes("0x7100")
    CMD_WR_NAND_OC2_1LINE = _getCmdBytes("0x7120")
    CMD_ER_NAND_OC2_1LINE = _getCmdBytes("0x7140")
    CMD_RD_NAND_OC2 = _getCmdBytes("0x7180")
    CMD_WR_NAND_OC2 = _getCmdBytes("0x71A0")
    CMD_ER_NAND_OC2 = _getCmdBytes("0x71C0")
    CMD_RD_NAND_OS1_MSB = _getCmdBytes("0x7200")
    CMD_WR_NAND_OS1_MSB = _getCmdBytes("0x7220")
    CMD_ER_NAND_OS1_MSB = _getCmdBytes("0x7240")
    CMD_RD_NAND_OS1_LSB = _getCmdBytes("0x7280")
    CMD_WR_NAND_OS1_LSB = _getCmdBytes("0x72A0")
    CMD_ER_NAND_OS1_LSB = _getCmdBytes("0x72C0")
    CMD_RD_NAND_OS2_MSB = _getCmdBytes("0x7300")
    CMD_WR_NAND_OS2_MSB = _getCmdBytes("0x7320")
    CMD_ER_NAND_OS2_MSB = _getCmdBytes("0x7340")
    CMD_RD_NAND_OS2_LSB = _getCmdBytes("0x7380")
    CMD_WR_NAND_OS2_LSB = _getCmdBytes("0x73A0")
    CMD_ER_NAND_OS2_LSB = _getCmdBytes("0x73C0")
    CMD_RD_NAND_SET_TIMER1 = _getCmdBytes("0x7780")
    CMD_WR_NAND_SET_TIMER1 = _getCmdBytes("0x77A0")
    CMD_ER_NAND_SET_TIMER1 = _getCmdBytes("0x77C0")
    CMD_RD_NAND_SET_TIMER2 = _getCmdBytes("0x7800")
    CMD_WR_NAND_SET_TIMER2 = _getCmdBytes("0x7820")
    CMD_ER_NAND_SET_TIMER2 = _getCmdBytes("0x7840")
    CMD_RD_NAND_TSLDD_Info = _getCmdBytes("0x7E80")
    CMD_WR_NAND_TSLDD_Info = _getCmdBytes("0x7EA0")
    CMD_ER_NAND_TSLDD_Info = _getCmdBytes("0x7EC0")
    CMD_RD_NAND_OC1_FLAG = _getCmdBytes("0x6300")
    CMD_WR_NAND_OC1_FLAG = _getCmdBytes("0x6320")
    CMD_ER_NAND_OC1_FLAG = _getCmdBytes("0x6340")
    CMD_RD_NAND_OC2_FLAG = _getCmdBytes("0x6380")
    CMD_WR_NAND_OC2_FLAG = _getCmdBytes("0x63A0")
    CMD_ER_NAND_OC2_FLAG = _getCmdBytes("0x63C0")
    CMD_RD_NAND_OS1_FLAG = _getCmdBytes("0x6400")
    CMD_WR_NAND_OS1_FLAG = _getCmdBytes("0x6420")
    CMD_ER_NAND_OS1_FLAG = _getCmdBytes("0x6440")
    CMD_RD_NAND_OS2_FLAG = _getCmdBytes("0x6480")
    CMD_WR_NAND_OS2_FLAG = _getCmdBytes("0x64A0")
    CMD_ER_NAND_OS2_FLAG = _getCmdBytes("0x64C0")
    CMD_RD_NAND_SET_OSLB_LUT1 = _getCmdBytes("0x6800")
    CMD_WR_NAND_SET_OSLB_LUT1 = _getCmdBytes("0x6820")
    CMD_ER_NAND_SET_OSLB_LUT1 = _getCmdBytes("0x6840")
    CMD_RD_NAND_LGD_OSLB_LUT1 = _getCmdBytes("0x6880")
    CMD_WR_NAND_LGD_OSLB_LUT1 = _getCmdBytes("0x68A0")
    CMD_ER_NAND_LGD_OSLB_LUT1 = _getCmdBytes("0x68C0")
    CMD_RD_NAND_SET_OSLB_Target_LUT = _getCmdBytes("0x7500")
    CMD_WR_NAND_SET_OSLB_Target_LUT = _getCmdBytes("0x7520")
    CMD_ER_NAND_SET_OSLB_Target_LUT = _getCmdBytes("0x7540")
    CMD_RD_NAND_LGD_OSLB_Target_LUT = _getCmdBytes("0x7580")
    CMD_WR_NAND_LGD_OSLB_Target_LUT = _getCmdBytes("0x75A0")
    CMD_ER_NAND_LGD_OSLB_Target_LUT = _getCmdBytes("0x75C0")
    CMD_RD_NAND_OSLB_PRNG_LUT = _getCmdBytes("0x7600")
    CMD_WR_NAND_OSLB_PRNG_LUT = _getCmdBytes("0x7620")
    CMD_ER_NAND_OSLB_PRNG_LUT = _getCmdBytes("0x7640")
    CMD_RD_NAND_SET_WCA_MAP = _getCmdBytes("0x7880")
    CMD_WR_NAND_SET_WCA_MAP = _getCmdBytes("0x78A0")
    CMD_ER_NAND_SET_WCA_MAP = _getCmdBytes("0x78C0")
    CMD_RD_NAND_LGD_WCA_MAP = _getCmdBytes("0x7900")
    CMD_WR_NAND_LGD_WCA_MAP = _getCmdBytes("0x7920")
    CMD_ER_NAND_LGD_WCA_MAP = _getCmdBytes("0x7940")
    CMD_RD_NAND_Y_PARAM = None            # T26 추가
    CMD_WR_NAND_Y_PARAM = None            # T26 추가
    CMD_ER_NAND_Y_PARAM = None            # T26 추가
    CMD_RD_NAND_ASIC_SCOPE = None         # T26 추가
    CMD_WR_NAND_ASIC_SCOPE = None         # T26 추가
    CMD_ER_NAND_ASIC_SCOPE = None         # T26 추가
    CMD_RD_NAND_SET_GWC = None            # T26 이름변경 : WCA_MAP -> GWC
    CMD_WR_NAND_SET_GWC = None            # T26 이름변경 : WCA_MAP -> GWC
    CMD_ER_NAND_SET_GWC = None            # T26 이름변경 : WCA_MAP -> GWC
    CMD_RD_NAND_LGD_GWC = None            # T26 이름변경 : WCA_MAP -> GWC
    CMD_WR_NAND_LGD_GWC = None            # T26 이름변경 : WCA_MAP -> GWC
    CMD_ER_NAND_LGD_GWC = None            # T26 이름변경 : WCA_MAP -> GWC
    CMD_RD_NAND_SET_TEMP_Gain_MAP = _getCmdBytes("0x7980")
    CMD_WR_NAND_SET_TEMP_Gain_MAP = _getCmdBytes("0x79A0")
    CMD_ER_NAND_SET_TEMP_Gain_MAP = _getCmdBytes("0x79C0")
    CMD_RD_NAND_LGD_TEMP_Gain_MAP = _getCmdBytes("0x7A00")
    CMD_WR_NAND_LGD_TEMP_Gain_MAP = _getCmdBytes("0x7A20")
    CMD_ER_NAND_LGD_TEMP_Gain_MAP = _getCmdBytes("0x7A40")
    CMD_RD_NAND_SET_TEMP_Offset_MAP = _getCmdBytes("0x7A80")
    CMD_WR_NAND_SET_TEMP_Offset_MAP = _getCmdBytes("0x7AA0")
    CMD_ER_NAND_SET_TEMP_Offset_MAP = _getCmdBytes("0x7AC0")
    CMD_RD_NAND_LGD_TEMP_Offset_MAP = _getCmdBytes("0x7B00")
    CMD_WR_NAND_LGD_TEMP_Offset_MAP = _getCmdBytes("0x7B20")
    CMD_ER_NAND_LGD_TEMP_Offset_MAP = _getCmdBytes("0x7B40")
    CMD_RD_NAND_SET_Remain_TEMP_MAP = _getCmdBytes("0x7B80")
    CMD_WR_NAND_SET_Remain_TEMP_MAP = _getCmdBytes("0x7BA0")
    CMD_ER_NAND_SET_Remain_TEMP_MAP = _getCmdBytes("0x7BC0")
    CMD_RD_NAND_LGD_Remain_TEMP_MAP = _getCmdBytes("0x7C00")
    CMD_WR_NAND_LGD_Remain_TEMP_MAP = _getCmdBytes("0x7C20")
    CMD_ER_NAND_LGD_Remain_TEMP_MAP = _getCmdBytes("0x7C40")
    CMD_RD_NAND_A2T_MAP1 = _getCmdBytes("0x7C80")
    CMD_WR_NAND_A2T_MAP1 = _getCmdBytes("0x7CA0")
    CMD_ER_NAND_A2T_MAP1 = _getCmdBytes("0x7CC0")
    CMD_RD_NAND_A2T_MAP2 = _getCmdBytes("0x7D00")
    CMD_WR_NAND_A2T_MAP2 = _getCmdBytes("0x7D20")
    CMD_ER_NAND_A2T_MAP2 = _getCmdBytes("0x7D40")
    CMD_RD_NAND_OSU_Info1 = _getCmdBytes("0x7D80")
    CMD_WR_NAND_OSU_Info1 = _getCmdBytes("0x7DA0")
    CMD_ER_NAND_OSU_Info1 = _getCmdBytes("0x7DC0")
    CMD_RD_NAND_OSU_Info2 = _getCmdBytes("0x7E00")
    CMD_WR_NAND_OSU_Info2 = _getCmdBytes("0x7E20")
    CMD_ER_NAND_OSU_Info2 = _getCmdBytes("0x7E40")
    CMD_RD_NAND_PYB_CPS_LUT = None        # T26 추가
    CMD_WR_NAND_PYB_CPS_LUT = None        # T26 추가
    CMD_ER_NAND_PYB_CPS_LUT = None        # T26 추가
    CMD_RD_NAND_PYB_EPM_LUT_IPA = None    # T26 추가
    CMD_WR_NAND_PYB_EPM_LUT_IPA = None    # T26 추가
    CMD_ER_NAND_PYB_EPM_LUT_IPA = None    # T26 추가
    CMD_RD_NAND_PYB_EPM_LUT_RS1 = None    # T26 추가
    CMD_WR_NAND_PYB_EPM_LUT_RS1 = None    # T26 추가
    CMD_ER_NAND_PYB_EPM_LUT_RS1 = None    # T26 추가
    CMD_RD_NAND_PYB_EPM_LUT_RS2 = None    # T26 추가
    CMD_WR_NAND_PYB_EPM_LUT_RS2 = None    # T26 추가
    CMD_ER_NAND_PYB_EPM_LUT_RS2 = None    # T26 추가
    CMD_RD_NAND_YB_LUTS = None            # T26 추가
    CMD_WR_NAND_YB_LUTS = None            # T26 추가
    CMD_ER_NAND_YB_LUTS = None            # T26 추가
    CMD_RD_NAND_F_PARAM_0 = None          # T26 추가
    CMD_WR_NAND_F_PARAM_0 = None          # T26 추가
    CMD_ER_NAND_F_PARAM_0 = None          # T26 추가
    CMD_RD_NAND_F_PARAM_1 = None          # T26 추가
    CMD_WR_NAND_F_PARAM_1 = None          # T26 추가
    CMD_ER_NAND_F_PARAM_1 = None          # T26 추가
    CMD_RD_NAND_PBI = None                # T26 추가
    CMD_WR_NAND_PBI = None                # T26 추가
    CMD_ER_NAND_PBI = None                # T26 추가
    CMD_RD_NAND_LTVSC_FLAG = None         # T26 추가
    CMD_WR_NAND_LTVSC_FLAG = None         # T26 추가
    CMD_ER_NAND_LTVSC_FLAG = None         # T26 추가
    CMD_RD_NAND_DBPC_FLAG = None          # T26 추가
    CMD_WR_NAND_DBPC_FLAG = None          # T26 추가
    CMD_ER_NAND_DBPC_FLAG = None          # T26 추가
    CMD_RD_NAND_I_PARAM = None            # T26 추가
    CMD_WR_NAND_I_PARAM = None            # T26 추가
    CMD_ER_NAND_I_PARAM = None            # T26 추가
    CMD_RD_NAND_PDM = _getCmdBytes("0x7400")
    CMD_YB_DDR_BRIDGE_RESET = _getCmdBytes("0x8040")
    CMD_OSLB_DDR_BRIDGE_RESET = _getCmdBytes("0x80C0")
    CMD_RD_NAND_SET_KMAP_LUT = None       # T26 추가
    CMD_WR_NAND_SET_KMAP_LUT = None       # T26 추가
    CMD_ER_NAND_SET_KMAP_LUT = None       # T26 추가
    CMD_RD_NAND_LGD_KMAP_LUT = None       # T26 추가
    CMD_WR_NAND_LGD_KMAP_LUT = None       # T26 추가
    CMD_ER_NAND_LGD_KMAP_LUT = None       # T26 추가
    CMD_RD_NAND_ASC_VGAIN_LUT = None      # T26 추가
    CMD_WR_NAND_ASC_VGAIN_LUT = None      # T26 추가
    CMD_ER_NAND_ASC_VGAIN_LUT = None      # T26 추가
    CMD_RD_NAND_OSLB_Info = None          # T26 추가
    CMD_WR_NAND_OSLB_Info = None          # T26 추가
    CMD_ER_NAND_OSLB_Info = None          # T26 추가
    CMD_RD_DDR_ALPHA1 = None              # T26 추가
    CMD_WR_DDR_ALPHA1 = None              # T26 추가
    CMD_RD_DDR_ALPHA2 = None              # T26 추가
    CMD_WR_DDR_ALPHA2 = None              # T26 추가
    CMD_RD_DDR_PHI = None                 # T26 추가
    CMD_WR_DDR_PHI = None                 # T26 추가
    CMD_RD_DDR_RT1 = _getCmdBytes("0x9000")
    CMD_WR_DDR_RT1 = _getCmdBytes("0x9020")
    CMD_RD_DDR_RT2 = _getCmdBytes("0x9080")
    CMD_WR_DDR_RT2 = _getCmdBytes("0x90A0")
    CMD_RD_DDR_RT_REF = _getCmdBytes("0x9100")
    CMD_WR_DDR_RT_REF = _getCmdBytes("0x9120")
    CMD_RD_DDR_YB_BUFFER = _getCmdBytes("0x9180")
    CMD_WR_DDR_YB_BUFFER = _getCmdBytes("0x91A0")
    CMD_RD_DDR_OC = _getCmdBytes("0x9200")
    CMD_WR_DDR_OC = _getCmdBytes("0x9220")
    CMD_RD_DDR_OS_MSB = _getCmdBytes("0x9280")
    CMD_WR_DDR_OS_MSB = _getCmdBytes("0x92A0")
    CMD_RD_DDR_OS_LSB = _getCmdBytes("0x9300")
    CMD_WR_DDR_OS_LSB = _getCmdBytes("0x9320")
    CMD_RD_DDR_OC_BUFFER = _getCmdBytes("0x9380")
    CMD_WR_DDR_OC_BUFFER = _getCmdBytes("0x93A0")
    CMD_RD_DDR_OS_BUFFER_MSB = _getCmdBytes("0x9400")
    CMD_WR_DDR_OS_BUFFER_MSB = _getCmdBytes("0x9420")
    CMD_RD_DDR_OS_BUFFER_LSB = _getCmdBytes("0x9480")
    CMD_WR_DDR_OS_BUFFER_LSB = _getCmdBytes("0x94A0")
    CMD_ELVSS_RISE = _getCmdBytes("0xA040")
    CMD_ELVSS_DROP = _getCmdBytes("0xA0C0")
    CMD_PGVDD_EN_RISE = None              # T26 추가
    CMD_PGVDD_EN_DROP = None              # T26 추가
    CMD_PGVDD_SEL_RISE = None             # T26 추가
    CMD_PGVDD_SEL_DROP = None             # T26 추가
    CMD_OFF_RS_START = _getCmdBytes("0xB040")
    CMD_OCU_START = _getCmdBytes("0xB0C0")
    CMD_OSU_START = _getCmdBytes("0xB140")
    CMD_ORS_START = None                  # T26 추가
    CMD_GDSD_RS = None                    # T26 추가
    CMD_BLACK_FRAME = _getCmdBytes("0xC0C0")
    CMD_PTG_R = _getCmdBytes("0xC140")
    CMD_PTG_W = _getCmdBytes("0xC148")
    CMD_PTG_G = _getCmdBytes("0xC150")
    CMD_PTG_B = _getCmdBytes("0xC158")
    CMD_PTG_OFF = _getCmdBytes("0xC1C0")
    CMD_ADDLD_READ = _getCmdBytes("0xD000")
    CMD_ADDLD_START = _getCmdBytes("0xD040")
    CMD_RD_DTC = None                     # T26 추가
    CMD_RD_ALPHA_DIFF_MAP = None          # T26 추가
    CMD_PHI_ALPHA_COPY = None             # T26 추가
    CMD_SCH_DONE_CHECK = None             # T26 추가


class GlobalVariableT26:
    ASIC_MODEL = "T26"
    RESOL = "UHD"                           # UHD, UHD+, QHD+, WQHD+
    nrow = 2160
    ncol = 30720
    LINE_LENGTH = 30720
    CB_LINE = 10
    APG_LINE = 19

    POT_LOG_PRINT = True

    # POT Enviroment
    POT_IP = "192.168.0.7"                  # POT board IP 주소
    PC_IP = "192.168.0.1"                  # PC IP 주소
    OP_PORTNUM = 4000                       # 일반 PC 명령어에 사용하는 포트
    PL_PORTNUM = 5000                       # Phase Lock 설정에 사용하는 포트
    PL_SETTING = "LGD_POT_A05_F08"          # Phase Lock 설정에 사용하는 Packet 값
    PC_COMMAND_DELAY = 0.002                # PC Command Packet 전송과 전송사이 delay 설정값 (second)
    POT_CONNECT_DELAY = 0.1                 # POT 연결 시, PL setting, POT ready Packet 전송사이 delay 설정값 (second)
    PC_MODE_CLEAR_DELAY = 0.6               # PC Mode Clear 완료 후 delay 설정값 (second)

    # POT Packet - Header
    HEADER_WR_0BYTE = 0                     # Header Packet 중 Write Length Index 값이 0Byte mode임을 표시
    HEADER_WR_1LINE = 1                     # Header Packet 중 Write Length Index 값이 1라인 mode임을 표시
    # POT Packet - Footer
    FOOTER_SUCCESS = 0                      # Footer Packet 중 동작 성공 여부 표시
    FOOTER_CHECKSUM_ERROR2 = 3              # Footer Packet 즁 T-Con <--> NAND 통신 Checksum 실패 여부 표시
    FOOTER_SENSING_FAIL = 4                 # Footer Packet 중 Sensing 실패 여부 표시
    FOOTER_WR_0BYTE = 0                     # Footer Packet 중 Read Length Index 값이 0Byte mode임을 표시
    FOOTER_WR_1LINE = 1                     # Footer Packet 중 Read Length Index 값이 1라인 mode임을 표시
    # POT Packet - Ack
    ACK_FLAG = 250                          # ACK Packet 임을 표시
    ACK_SUCCESS = 0                         # ACK Packet 즁 동작 성공 여부 표시
    ACK_TIMEOUT_TCON = 1                    # ACK Packet 즁 T-Con에서 timeout 여부 표시
    ACK_CHECKSUM_ERROR1 = 2                 # ACK Packet 즁 POT <--> T-Con 통신 Checksum 실패 여부 표시
    ACK_CHECKSUM_ERROR2 = 3                 # ACK Packet 즁 T-Con <--> NAND 통신 Checksum 실패 여부 표시

    # PC Command
    CMD_TCON_RESET = _getCmdBytes("0x0040")
    CMD_POWER_RESET = _getCmdBytes("0x00C0")                # T26 추가
    CMD_SET_EMERGENCY = _getCmdBytes("0x1040")              # T22 추가
    CMD_CLR_EMERGENCY = _getCmdBytes("0x10C0")              # T22 추가
    CMD_SET_PCMODE = _getCmdBytes("0x2040")
    CMD_CLR_PCMODE = _getCmdBytes("0x20C0")
    CMD_RD_TCON_VPARAM = _getCmdBytes("0x3000")
    CMD_WR_TCON_VPARAM = _getCmdBytes("0x3020")
    CMD_RD_OPARAM = _getCmdBytes("0x3080")
    CMD_WR_OPARAM = _getCmdBytes("0x30A0")
    CMD_SEN_AVC = _getCmdBytes("0x4000")
    CMD_SEN_REF = _getCmdBytes("0x4080")
    CMD_SEN_SMODE_R = _getCmdBytes("0x5000")
    CMD_SEN_SMODE_W = _getCmdBytes("0x5008")
    CMD_SEN_SMODE_G = _getCmdBytes("0x5010")
    CMD_SEN_SMODE_B = _getCmdBytes("0x5018")
    CMD_SEN_FMODE_R = _getCmdBytes("0x5080")
    CMD_SEN_FMODE_W = _getCmdBytes("0x5088")
    CMD_SEN_FMODE_G = _getCmdBytes("0x5090")
    CMD_SEN_FMODE_B = _getCmdBytes("0x5098")
    CMD_SEN_SMODE_4C = _getCmdBytes("0x5180")               # T22 추가
    CMD_SEN_FMODE_4C = _getCmdBytes("0x5200")               # T22 추가
    CMD_SEN_AMODE_R = _getCmdBytes("0x5100")                # T22 추가
    CMD_SEN_AMODE_W = _getCmdBytes("0x5108")                # T22 추가
    CMD_SEN_AMODE_G = _getCmdBytes("0x5110")                # T22 추가
    CMD_SEN_AMODE_B = _getCmdBytes("0x5118")                # T22 추가
    CMD_SEN_ADPD5_R = _getCmdBytes("0x5280")                # T22 추가
    CMD_SEN_ADPD5_W = _getCmdBytes("0x5288")                # T22 추가
    CMD_SEN_ADPD5_G = _getCmdBytes("0x5290")                # T22 추가
    CMD_SEN_ADPD5_B = _getCmdBytes("0x5298")                # T22 추가
    CMD_SEN_ADPD5_4C = _getCmdBytes("0x5300")               # T22 추가
    CMD_SEN_OFFRF_MODE_R = _getCmdBytes("0x5380")           # T26 추가
    CMD_SEN_OFFRF_MODE_W = _getCmdBytes("0x5388")           # T26 추가
    CMD_SEN_OFFRF_MODE_G = _getCmdBytes("0x5390")           # T26 추가
    CMD_SEN_OFFRF_MODE_B = _getCmdBytes("0x5398")           # T26 추가
    CMD_SEN_OFFRF_MODE_4C = _getCmdBytes("0x5C00")          # T26 추가
    CMD_RD_NAND_SET_LPARAM = _getCmdBytes("0x7480")
    CMD_WR_NAND_SET_LPARAM = _getCmdBytes("0x74A0")
    CMD_ER_NAND_SET_LPARAM = _getCmdBytes("0x74C0")
    CMD_RD_NAND_LPARAM = _getCmdBytes("0x6080")
    CMD_WR_NAND_LPARAM = _getCmdBytes("0x60A0")
    CMD_ER_NAND_LPARAM = _getCmdBytes("0x60C0")
    CMD_RD_NAND_SET_VPARAM = _getCmdBytes("0x6100")
    CMD_WR_NAND_SET_VPARAM = _getCmdBytes("0x6120")
    CMD_ER_NAND_SET_VPARAM = _getCmdBytes("0x6140")
    CMD_RD_NAND_LGD_VPARAM = _getCmdBytes("0x6180")
    CMD_WR_NAND_LGD_VPARAM = _getCmdBytes("0x61A0")
    CMD_ER_NAND_LGD_VPARAM = _getCmdBytes("0x61C0")
    CMD_RD_NAND_RS1_FLAG = _getCmdBytes("0x6200")
    CMD_WR_NAND_RS1_FLAG = _getCmdBytes("0x6220")
    CMD_ER_NAND_RS1_FLAG = _getCmdBytes("0x6240")
    CMD_RD_NAND_RS2_FLAG = _getCmdBytes("0x6280")
    CMD_WR_NAND_RS2_FLAG = _getCmdBytes("0x62A0")
    CMD_ER_NAND_RS2_FLAG = _getCmdBytes("0x62C0")
    CMD_RD_NAND_YB_INFO1 = _getCmdBytes("0x6500")           # T26 추가
    CMD_WR_NAND_YB_INFO1 = _getCmdBytes("0x6520")           # T26 추가
    CMD_ER_NAND_YB_INFO1 = _getCmdBytes("0x6540")           # T26 추가
    CMD_RD_NAND_YB_INFO2 = _getCmdBytes("0x6580")           # T26 추가
    CMD_WR_NAND_YB_INFO2 = _getCmdBytes("0x65A0")           # T26 추가
    CMD_ER_NAND_YB_INFO2 = _getCmdBytes("0x65C0")           # T26 추가
    CMD_RD_NAND_BLC1 = None
    CMD_WR_NAND_BLC1 = None
    CMD_ER_NAND_BLC1 = None
    CMD_RD_NAND_BLC2 = None
    CMD_WR_NAND_BLC2 = None
    CMD_ER_NAND_BLC2 = None
    CMD_RD_NAND_CRP1_FLAG = _getCmdBytes("0x6600")
    CMD_WR_NAND_CRP1_FLAG = _getCmdBytes("0x6620")
    CMD_ER_NAND_CRP1_FLAG = _getCmdBytes("0x6640")
    CMD_RD_NAND_CRP2_FLAG = _getCmdBytes("0x6680")
    CMD_WR_NAND_CRP2_FLAG = _getCmdBytes("0x66A0")
    CMD_ER_NAND_CRP2_FLAG = _getCmdBytes("0x66C0")
    CMD_WR_NAND_CME_PHI1 = None
    CMD_RD_NAND_CME_PHI1 = None
    CMD_ER_NAND_CME_PHI1 = None
    CMD_WR_NAND_CME_PHI2 = None
    CMD_RD_NAND_CME_PHI2 = None
    CMD_ER_NAND_CME_PHI2 = None
    CMD_RD_NAND_CME_ALPHA1 = _getCmdBytes("0x6700")
    CMD_WR_NAND_CME_ALPHA1 = _getCmdBytes("0x6720")
    CMD_ER_NAND_CME_ALPHA1 = _getCmdBytes("0x6740")
    CMD_RD_NAND_CME_ALPHA2 = _getCmdBytes("0x6780")
    CMD_WR_NAND_CME_ALPHA2 = _getCmdBytes("0x67A0")
    CMD_ER_NAND_CME_ALPHA2 = _getCmdBytes("0x67C0")
    CMD_RD_NAND_ATCB = _getCmdBytes("0x6B80")               # T26 추가
    CMD_WR_NAND_ATCB = _getCmdBytes("0x6BA0")               # T26 추가
    CMD_ER_NAND_ATCB = _getCmdBytes("0x6BC0")               # T26 추가
    CMD_RD_NAND_GVC = _getCmdBytes("0x6C00")                # T26 추가
    CMD_WR_NAND_GVC = _getCmdBytes("0x6C20")                # T26 추가
    CMD_ER_NAND_GVC = _getCmdBytes("0x6C40")                # T26 추가
    CMD_RD_NAND_IPA_PHI = _getCmdBytes("0x6C80")            # T26 추가
    CMD_WR_NAND_IPA_PHI = _getCmdBytes("0x6CA0")            # T26 추가
    CMD_ER_NAND_IPA_PHI = _getCmdBytes("0x6CC0")            # T26 추가
    CMD_RD_NAND_PHI1 = _getCmdBytes("0x6D00")               # T26 추가
    CMD_WR_NAND_PHI1 = _getCmdBytes("0x6D20")               # T26 추가
    CMD_ER_NAND_PHI1 = _getCmdBytes("0x6D40")               # T26 추가
    CMD_RD_NAND_PHI2 = _getCmdBytes("0x6D80")               # T26 추가
    CMD_WR_NAND_PHI2 = _getCmdBytes("0x6DA0")               # T26 추가
    CMD_ER_NAND_PHI2 = _getCmdBytes("0x6DC0")               # T26 추가
    CMD_RD_NAND_PHI_YCB1 = _getCmdBytes("0x6E00")           # T26 추가
    CMD_WR_NAND_PHI_YCB1 = _getCmdBytes("0x6E20")           # T26 추가
    CMD_ER_NAND_PHI_YCB1 = _getCmdBytes("0x6E40")           # T26 추가
    CMD_RD_NAND_PHI_YCB2 = _getCmdBytes("0x6E80")           # T26 추가
    CMD_WR_NAND_PHI_YCB2 = _getCmdBytes("0x6EA0")           # T26 추가
    CMD_ER_NAND_PHI_YCB2 = _getCmdBytes("0x6EC0")           # T26 추가
    CMD_RD_NAND_ALPHA1 = _getCmdBytes("0x7300")             # T26 추가
    CMD_WR_NAND_ALPHA1 = _getCmdBytes("0x7320")             # T26 추가
    CMD_ER_NAND_ALPHA1 = _getCmdBytes("0x7340")             # T26 추가
    CMD_RD_NAND_ALPHA2 = _getCmdBytes("0x7380")             # T26 추가
    CMD_WR_NAND_ALPHA2 = _getCmdBytes("0x73A0")             # T26 추가
    CMD_ER_NAND_ALPHA2 = _getCmdBytes("0x73C0")             # T26 추가
    CMD_RD_NAND_IPA_ALPHA = _getCmdBytes("0x7F00")          # T26 추가
    CMD_WR_NAND_IPA_ALPHA = _getCmdBytes("0x7F20")          # T26 추가
    CMD_ER_NAND_IPA_ALPHA = _getCmdBytes("0x7F40")          # T26 추가
    CMD_RD_NAND_CB = None
    CMD_WR_NAND_CB = None
    CMD_ER_NAND_CB = None
    CMD_RD_NAND_APG = None
    CMD_WR_NAND_APG = None
    CMD_ER_NAND_APG = None
    CMD_RD_NAND_YCB = _getCmdBytes("0x6F00")
    CMD_WR_NAND_YCB = _getCmdBytes("0x6F20")
    CMD_ER_NAND_YCB = _getCmdBytes("0x6F40")
    CMD_RD_NAND_RT_REF = _getCmdBytes("0x6F80")
    CMD_WR_NAND_RT_REF = _getCmdBytes("0x6FA0")
    CMD_ER_NAND_RT_REF = _getCmdBytes("0x6FC0")
    CMD_RD_NAND_SET_PDCS_LUT1 = None
    CMD_WR_NAND_SET_PDCS_LUT1 = None
    CMD_ER_NAND_SET_PDCS_LUT1 = None
    CMD_RD_NAND_SET_PDCS_LUT2 = None
    CMD_WR_NAND_SET_PDCS_LUT2 = None
    CMD_ER_NAND_SET_PDCS_LUT2 = None
    CMD_RD_NAND_S_PARAM = _getCmdBytes("0x6000")
    CMD_WR_NAND_S_PARAM = _getCmdBytes("0x6020")
    CMD_ER_NAND_S_PARAM = _getCmdBytes("0x6040")
    CMD_RD_NAND_G_PARAM = _getCmdBytes("0x6900")
    CMD_WR_NAND_G_PARAM = _getCmdBytes("0x6920")
    CMD_ER_NAND_G_PARAM = _getCmdBytes("0x6940")
    CMD_RD_NAND_TIMER1 = _getCmdBytes("0x6980")
    CMD_WR_NAND_TIMER1 = _getCmdBytes("0x69A0")
    CMD_ER_NAND_TIMER1 = _getCmdBytes("0x69C0")
    CMD_RD_NAND_TIMER2 = _getCmdBytes("0x6A00")
    CMD_WR_NAND_TIMER2 = _getCmdBytes("0x6A20")
    CMD_ER_NAND_TIMER2 = _getCmdBytes("0x6A40")
    CMD_RD_NAND_TEMP1 = _getCmdBytes("0x6A80")
    CMD_WR_NAND_TEMP1 = _getCmdBytes("0x6AA0")
    CMD_ER_NAND_TEMP1 = _getCmdBytes("0x6AC0")
    CMD_RD_NAND_TEMP2 = _getCmdBytes("0x6B00")
    CMD_WR_NAND_TEMP2 = _getCmdBytes("0x6B20")
    CMD_ER_NAND_TEMP2 = _getCmdBytes("0x6B40")
    CMD_RD_NAND_OC1 = _getCmdBytes("0x7000")
    CMD_WR_NAND_OC1 = _getCmdBytes("0x7020")
    CMD_ER_NAND_OC1 = _getCmdBytes("0x7040")
    CMD_RD_NAND_OC1_1LINE = None
    CMD_WR_NAND_OC1_1LINE = None
    CMD_ER_NAND_OC1_1LINE = None
    CMD_RD_NAND_OC2 = _getCmdBytes("0x7080")
    CMD_WR_NAND_OC2 = _getCmdBytes("0x70A0")
    CMD_ER_NAND_OC2 = _getCmdBytes("0x70C0")
    CMD_RD_NAND_OC2_1LINE = None
    CMD_WR_NAND_OC2_1LINE = None
    CMD_ER_NAND_OC2_1LINE = None
    CMD_RD_NAND_OS1_MSB = _getCmdBytes("0x7100")
    CMD_WR_NAND_OS1_MSB = _getCmdBytes("0x7120")
    CMD_ER_NAND_OS1_MSB = _getCmdBytes("0x7140")
    CMD_RD_NAND_OS1_LSB = _getCmdBytes("0x7180")
    CMD_WR_NAND_OS1_LSB = _getCmdBytes("0x71A0")
    CMD_ER_NAND_OS1_LSB = _getCmdBytes("0x71C0")
    CMD_RD_NAND_OS2_MSB = _getCmdBytes("0x7200")
    CMD_WR_NAND_OS2_MSB = _getCmdBytes("0x7220")
    CMD_ER_NAND_OS2_MSB = _getCmdBytes("0x7240")
    CMD_RD_NAND_OS2_LSB = _getCmdBytes("0x7280")
    CMD_WR_NAND_OS2_LSB = _getCmdBytes("0x72A0")
    CMD_ER_NAND_OS2_LSB = _getCmdBytes("0x72C0")
    CMD_RD_NAND_SET_TIMER1 = _getCmdBytes("0x7780")
    CMD_WR_NAND_SET_TIMER1 = _getCmdBytes("0x77A0")
    CMD_ER_NAND_SET_TIMER1 = _getCmdBytes("0x77C0")
    CMD_RD_NAND_SET_TIMER2 = _getCmdBytes("0x7800")
    CMD_WR_NAND_SET_TIMER2 = _getCmdBytes("0x7820")
    CMD_ER_NAND_SET_TIMER2 = _getCmdBytes("0x7840")
    CMD_RD_NAND_TSLDD_Info = _getCmdBytes("0x7E80")
    CMD_WR_NAND_TSLDD_Info = _getCmdBytes("0x7EA0")
    CMD_ER_NAND_TSLDD_Info = _getCmdBytes("0x7EC0")
    CMD_RD_NAND_OC1_FLAG = _getCmdBytes("0x6300")
    CMD_WR_NAND_OC1_FLAG = _getCmdBytes("0x6320")
    CMD_ER_NAND_OC1_FLAG = _getCmdBytes("0x6340")
    CMD_RD_NAND_OC2_FLAG = _getCmdBytes("0x6380")
    CMD_WR_NAND_OC2_FLAG = _getCmdBytes("0x63A0")
    CMD_ER_NAND_OC2_FLAG = _getCmdBytes("0x63C0")
    CMD_RD_NAND_OS1_FLAG = _getCmdBytes("0x6400")
    CMD_WR_NAND_OS1_FLAG = _getCmdBytes("0x6420")
    CMD_ER_NAND_OS1_FLAG = _getCmdBytes("0x6440")
    CMD_RD_NAND_OS2_FLAG = _getCmdBytes("0x6480")
    CMD_WR_NAND_OS2_FLAG = _getCmdBytes("0x64A0")
    CMD_ER_NAND_OS2_FLAG = _getCmdBytes("0x64C0")
    CMD_RD_NAND_SET_OSLB_LUT1 = _getCmdBytes("0x6800")
    CMD_WR_NAND_SET_OSLB_LUT1 = _getCmdBytes("0x6820")
    CMD_ER_NAND_SET_OSLB_LUT1 = _getCmdBytes("0x6840")
    CMD_RD_NAND_LGD_OSLB_LUT1 = _getCmdBytes("0x6880")
    CMD_WR_NAND_LGD_OSLB_LUT1 = _getCmdBytes("0x68A0")
    CMD_ER_NAND_LGD_OSLB_LUT1 = _getCmdBytes("0x68C0")
    CMD_RD_NAND_SET_OSLB_Target_LUT = _getCmdBytes("0x7500")
    CMD_WR_NAND_SET_OSLB_Target_LUT = _getCmdBytes("0x7520")
    CMD_ER_NAND_SET_OSLB_Target_LUT = _getCmdBytes("0x7540")
    CMD_RD_NAND_LGD_OSLB_Target_LUT = _getCmdBytes("0x7580")
    CMD_WR_NAND_LGD_OSLB_Target_LUT = _getCmdBytes("0x75A0")
    CMD_ER_NAND_LGD_OSLB_Target_LUT = _getCmdBytes("0x75C0")
    CMD_RD_NAND_OSLB_PRNG_LUT = _getCmdBytes("0x7600")
    CMD_WR_NAND_OSLB_PRNG_LUT = _getCmdBytes("0x7620")
    CMD_ER_NAND_OSLB_PRNG_LUT = _getCmdBytes("0x7640")
    CMD_RD_NAND_SET_WCA_MAP = None
    CMD_WR_NAND_SET_WCA_MAP = None
    CMD_ER_NAND_SET_WCA_MAP = None
    CMD_RD_NAND_LGD_WCA_MAP = None
    CMD_WR_NAND_LGD_WCA_MAP = None
    CMD_ER_NAND_LGD_WCA_MAP = None
    CMD_RD_NAND_Y_PARAM = _getCmdBytes("0x7680")            # T26 추가
    CMD_WR_NAND_Y_PARAM = _getCmdBytes("0x76A0")            # T26 추가
    CMD_ER_NAND_Y_PARAM = _getCmdBytes("0x76C0")            # T26 추가
    CMD_RD_NAND_ASIC_SCOPE = _getCmdBytes("0x7700")         # T26 추가
    CMD_WR_NAND_ASIC_SCOPE = _getCmdBytes("0x7720")         # T26 추가
    CMD_ER_NAND_ASIC_SCOPE = _getCmdBytes("0x7740")         # T26 추가
    CMD_RD_NAND_SET_GWC = _getCmdBytes("0x7880")            # T26 이름변경 : WCA_MAP -> GWC
    CMD_WR_NAND_SET_GWC = _getCmdBytes("0x78A0")            # T26 이름변경 : WCA_MAP -> GWC
    CMD_ER_NAND_SET_GWC = _getCmdBytes("0x78C0")            # T26 이름변경 : WCA_MAP -> GWC
    CMD_RD_NAND_LGD_GWC = _getCmdBytes("0x7900")            # T26 이름변경 : WCA_MAP -> GWC
    CMD_WR_NAND_LGD_GWC = _getCmdBytes("0x7920")            # T26 이름변경 : WCA_MAP -> GWC
    CMD_ER_NAND_LGD_GWC = _getCmdBytes("0x7940")            # T26 이름변경 : WCA_MAP -> GWC
    CMD_RD_NAND_SET_TEMP_Gain_MAP = _getCmdBytes("0x7980")
    CMD_WR_NAND_SET_TEMP_Gain_MAP = _getCmdBytes("0x79A0")
    CMD_ER_NAND_SET_TEMP_Gain_MAP = _getCmdBytes("0x79C0")
    CMD_RD_NAND_LGD_TEMP_Gain_MAP = _getCmdBytes("0x7A00")
    CMD_WR_NAND_LGD_TEMP_Gain_MAP = _getCmdBytes("0x7A20")
    CMD_ER_NAND_LGD_TEMP_Gain_MAP = _getCmdBytes("0x7A40")
    CMD_RD_NAND_SET_TEMP_Offset_MAP = _getCmdBytes("0x7A80")
    CMD_WR_NAND_SET_TEMP_Offset_MAP = _getCmdBytes("0x7AA0")
    CMD_ER_NAND_SET_TEMP_Offset_MAP = _getCmdBytes("0x7AC0")
    CMD_RD_NAND_LGD_TEMP_Offset_MAP = _getCmdBytes("0x7B00")
    CMD_WR_NAND_LGD_TEMP_Offset_MAP = _getCmdBytes("0x7B20")
    CMD_ER_NAND_LGD_TEMP_Offset_MAP = _getCmdBytes("0x7B40")
    CMD_RD_NAND_SET_Remain_TEMP_MAP = _getCmdBytes("0x7B80")
    CMD_WR_NAND_SET_Remain_TEMP_MAP = _getCmdBytes("0x7BA0")
    CMD_ER_NAND_SET_Remain_TEMP_MAP = _getCmdBytes("0x7BC0")
    CMD_RD_NAND_LGD_Remain_TEMP_MAP = _getCmdBytes("0x7C00")
    CMD_WR_NAND_LGD_Remain_TEMP_MAP = _getCmdBytes("0x7C20")
    CMD_ER_NAND_LGD_Remain_TEMP_MAP = _getCmdBytes("0x7C40")
    CMD_RD_NAND_A2T_MAP1 = _getCmdBytes("0x7C80")
    CMD_WR_NAND_A2T_MAP1 = _getCmdBytes("0x7CA0")
    CMD_ER_NAND_A2T_MAP1 = _getCmdBytes("0x7CC0")
    CMD_RD_NAND_A2T_MAP2 = _getCmdBytes("0x7D00")
    CMD_WR_NAND_A2T_MAP2 = _getCmdBytes("0x7D20")
    CMD_ER_NAND_A2T_MAP2 = _getCmdBytes("0x7D40")
    CMD_RD_NAND_OSU_Info1 = _getCmdBytes("0x7D80")
    CMD_WR_NAND_OSU_Info1 = _getCmdBytes("0x7DA0")
    CMD_ER_NAND_OSU_Info1 = _getCmdBytes("0x7DC0")
    CMD_RD_NAND_OSU_Info2 = _getCmdBytes("0x7E00")
    CMD_WR_NAND_OSU_Info2 = _getCmdBytes("0x7E20")
    CMD_ER_NAND_OSU_Info2 = _getCmdBytes("0x7E40")
    CMD_RD_NAND_PYB_CPS_LUT = _getCmdBytes("0x7F80")        # T26 추가
    CMD_WR_NAND_PYB_CPS_LUT = _getCmdBytes("0x7FA0")        # T26 추가
    CMD_ER_NAND_PYB_CPS_LUT = _getCmdBytes("0x7FC0")        # T26 추가
    CMD_RD_NAND_PYB_EPM_LUT_IPA = _getCmdBytes("0x8100")    # T26 추가
    CMD_WR_NAND_PYB_EPM_LUT_IPA = _getCmdBytes("0x8120")    # T26 추가
    CMD_ER_NAND_PYB_EPM_LUT_IPA = _getCmdBytes("0x8140")    # T26 추가
    CMD_RD_NAND_PYB_EPM_LUT_RS1 = _getCmdBytes("0x8300")    # T26 추가
    CMD_WR_NAND_PYB_EPM_LUT_RS1 = _getCmdBytes("0x8320")    # T26 추가
    CMD_ER_NAND_PYB_EPM_LUT_RS1 = _getCmdBytes("0x8340")    # T26 추가
    CMD_RD_NAND_PYB_EPM_LUT_RS2 = _getCmdBytes("0x8380")    # T26 추가
    CMD_WR_NAND_PYB_EPM_LUT_RS2 = _getCmdBytes("0x83A0")    # T26 추가
    CMD_ER_NAND_PYB_EPM_LUT_RS2 = _getCmdBytes("0x83C0")    # T26 추가
    CMD_RD_NAND_YB_LUTS = _getCmdBytes("0x8400")            # T26 추가
    CMD_WR_NAND_YB_LUTS = _getCmdBytes("0x8420")            # T26 추가
    CMD_ER_NAND_YB_LUTS = _getCmdBytes("0x8440")            # T26 추가
    CMD_RD_NAND_F_PARAM_0 = _getCmdBytes("0x8480")          # T26 추가
    CMD_WR_NAND_F_PARAM_0 = _getCmdBytes("0x84A0")          # T26 추가
    CMD_ER_NAND_F_PARAM_0 = _getCmdBytes("0x84C0")          # T26 추가
    CMD_RD_NAND_F_PARAM_1 = _getCmdBytes("0x8500")          # T26 추가
    CMD_WR_NAND_F_PARAM_1 = _getCmdBytes("0x8520")          # T26 추가
    CMD_ER_NAND_F_PARAM_1 = _getCmdBytes("0x8540")          # T26 추가
    CMD_RD_NAND_PBI = _getCmdBytes("0x8580")                # T26 추가
    CMD_WR_NAND_PBI = _getCmdBytes("0x85A0")                # T26 추가
    CMD_ER_NAND_PBI = _getCmdBytes("0x85C0")                # T26 추가
    CMD_RD_NAND_LTVSC_FLAG = _getCmdBytes("0x8600")         # T26 추가
    CMD_WR_NAND_LTVSC_FLAG = _getCmdBytes("0x8620")         # T26 추가
    CMD_ER_NAND_LTVSC_FLAG = _getCmdBytes("0x8640")         # T26 추가
    CMD_RD_NAND_DBPC_FLAG = _getCmdBytes("0x8680")          # T26 추가
    CMD_WR_NAND_DBPC_FLAG = _getCmdBytes("0x86A0")          # T26 추가
    CMD_ER_NAND_DBPC_FLAG = _getCmdBytes("0x86C0")          # T26 추가
    CMD_RD_NAND_I_PARAM = _getCmdBytes("0x8700")            # T26 추가
    CMD_WR_NAND_I_PARAM = _getCmdBytes("0x8720")            # T26 추가
    CMD_ER_NAND_I_PARAM = _getCmdBytes("0x8740")            # T26 추가
    CMD_RD_NAND_PDM = _getCmdBytes("0x7400")
    CMD_YB_DDR_BRIDGE_RESET = _getCmdBytes("0x8040")
    CMD_OSLB_DDR_BRIDGE_RESET = _getCmdBytes("0x80C0")
    CMD_RD_NAND_SET_KMAP_LUT = _getCmdBytes("0x8780")       # T26 추가
    CMD_WR_NAND_SET_KMAP_LUT = _getCmdBytes("0x87A0")       # T26 추가
    CMD_ER_NAND_SET_KMAP_LUT = _getCmdBytes("0x87C0")       # T26 추가
    CMD_RD_NAND_LGD_KMAP_LUT = _getCmdBytes("0x8800")       # T26 추가
    CMD_WR_NAND_LGD_KMAP_LUT = _getCmdBytes("0x8820")       # T26 추가
    CMD_ER_NAND_LGD_KMAP_LUT = _getCmdBytes("0x8840")       # T26 추가
    CMD_RD_NAND_ASC_VGAIN_LUT = _getCmdBytes("0x8880")      # T26 추가
    CMD_WR_NAND_ASC_VGAIN_LUT = _getCmdBytes("0x88A0")      # T26 추가
    CMD_ER_NAND_ASC_VGAIN_LUT = _getCmdBytes("0x88C0")      # T26 추가
    CMD_RD_NAND_OSLB_Info = _getCmdBytes("0x8900")          # T26 추가
    CMD_WR_NAND_OSLB_Info = _getCmdBytes("0x8920")          # T26 추가
    CMD_ER_NAND_OSLB_Info = _getCmdBytes("0x8940")          # T26 추가
    CMD_RD_DDR_ALPHA1 = _getCmdBytes("0x9000")              # T26 추가
    CMD_WR_DDR_ALPHA1 = _getCmdBytes("0x9020")              # T26 추가
    CMD_RD_DDR_ALPHA2 = _getCmdBytes("0x9080")              # T26 추가
    CMD_WR_DDR_ALPHA2 = _getCmdBytes("0x90A0")              # T26 추가
    CMD_RD_DDR_PHI = _getCmdBytes("0x9100")                 # T26 추가
    CMD_WR_DDR_PHI = _getCmdBytes("0x9120")                 # T26 추가
    CMD_RD_DDR_RT_REF = _getCmdBytes("0x9180")
    CMD_WR_DDR_RT_REF = _getCmdBytes("0x91A0")
    CMD_RD_DDR_YB_BUFFER = None
    CMD_WR_DDR_YB_BUFFER = None
    CMD_RD_DDR_OC = _getCmdBytes("0x9200")
    CMD_WR_DDR_OC = _getCmdBytes("0x9220")
    CMD_RD_DDR_OS_MSB = _getCmdBytes("0x9280")
    CMD_WR_DDR_OS_MSB = _getCmdBytes("0x92A0")
    CMD_RD_DDR_OS_LSB = _getCmdBytes("0x9300")
    CMD_WR_DDR_OS_LSB = _getCmdBytes("0x9320")
    CMD_RD_DDR_OC_BUFFER = None
    CMD_WR_DDR_OC_BUFFER = None
    CMD_RD_DDR_OS_BUFFER_MSB = None
    CMD_WR_DDR_OS_BUFFER_MSB = None
    CMD_RD_DDR_OS_BUFFER_LSB = None
    CMD_WR_DDR_OS_BUFFER_LSB = None
    CMD_RD_DDR_RT1 = _getCmdBytes("0x9380")
    CMD_WR_DDR_RT1 = _getCmdBytes("0x93A0")
    CMD_RD_DDR_RT2 = _getCmdBytes("0x9400")
    CMD_WR_DDR_RT2 = _getCmdBytes("0x9420")
    CMD_ELVSS_RISE = _getCmdBytes("0xA040")
    CMD_ELVSS_DROP = _getCmdBytes("0xA0C0")
    CMD_PGVDD_EN_RISE = _getCmdBytes("0xA240")              # T26 추가
    CMD_PGVDD_EN_DROP = _getCmdBytes("0xA2C0")              # T26 추가
    CMD_PGVDD_SEL_RISE = _getCmdBytes("0xA340")             # T26 추가
    CMD_PGVDD_SEL_DROP = _getCmdBytes("0xA3C0")             # T26 추가
    CMD_OFF_RS_START = _getCmdBytes("0xB040")
    CMD_OCU_START = _getCmdBytes("0xB0C0")
    CMD_OSU_START = _getCmdBytes("0xB140")
    CMD_ORS_START = _getCmdBytes("0xB1C0")                  # T26 추가
    CMD_GDSD_RS = _getCmdBytes("0xC040")                    # T26 추가
    CMD_BLACK_FRAME = _getCmdBytes("0xC0C0")
    CMD_PTG_R = _getCmdBytes("0xC140")
    CMD_PTG_W = _getCmdBytes("0xC148")
    CMD_PTG_G = _getCmdBytes("0xC150")
    CMD_PTG_B = _getCmdBytes("0xC158")
    CMD_PTG_OFF = _getCmdBytes("0xC1C0")
    CMD_ADDLD_READ = _getCmdBytes("0xD000")
    CMD_ADDLD_START = _getCmdBytes("0xD040")
    CMD_RD_DTC = _getCmdBytes("0xE000")                     # T26 추가
    CMD_RD_ALPHA_DIFF_MAP = _getCmdBytes("0xE080")          # T26 추가
    CMD_PHI_ALPHA_COPY = _getCmdBytes("0xE100")             # T26 추가
    CMD_RD_NAND_IPA = _getCmdBytes("0xE180")
    CMD_WR_NAND_IPA = _getCmdBytes("0xE1A0")
    CMD_ER_NAND_IPA = _getCmdBytes("0xE1C0")
    CMD_RD_NAND_YB1 = _getCmdBytes("0xE200")
    CMD_WR_NAND_YB1 = _getCmdBytes("0xE220")
    CMD_ER_NAND_YB1 = _getCmdBytes("0xE240")
    CMD_RD_NAND_YB2 = _getCmdBytes("0xE280")
    CMD_WR_NAND_YB2 = _getCmdBytes("0xE2A0")
    CMD_ER_NAND_YB2 = _getCmdBytes("0xE2C0")
    CMD_RD_NAND_YB_YCB1 = _getCmdBytes("0xE300")
    CMD_WR_NAND_YB_YCB1 = _getCmdBytes("0xE320")
    CMD_ER_NAND_YB_YCB1 = _getCmdBytes("0xE340")
    CMD_RD_NAND_YB_YCB2 = _getCmdBytes("0xE380")
    CMD_WR_NAND_YB_YCB2 = _getCmdBytes("0xE3A0")
    CMD_ER_NAND_YB_YCB2 = _getCmdBytes("0xE3C0")
    CMD_SCH_DONE_CHECK = _getCmdBytes("0xF040")             # T26 추가



class GlobalDataContainer:
    r"""
    전역 Data Array 모음 (class variables)
    """
    # Sensing Data Memory (for Transfer)
    rSensContainer      = np.zeros((GlobalVariableT26.nrow, int(GlobalVariableT26.ncol/8)), dtype = np.int16)
    wSensContainer      = np.zeros((GlobalVariableT26.nrow, int(GlobalVariableT26.ncol/8)), dtype = np.int16)
    gSensContainer      = np.zeros((GlobalVariableT26.nrow, int(GlobalVariableT26.ncol/8)), dtype = np.int16)
    bSensContainer      = np.zeros((GlobalVariableT26.nrow, int(GlobalVariableT26.ncol/8)), dtype = np.int16)
    # Compensation Data Memory (for Transfer)
    rPhiContainer       = np.zeros((GlobalVariableT26.nrow, int(GlobalVariableT26.ncol/8)), dtype = np.int16)
    rAlphaContainer     = np.zeros((GlobalVariableT26.nrow, int(GlobalVariableT26.ncol/8)), dtype = np.int16)
    wPhiContainer       = np.zeros((GlobalVariableT26.nrow, int(GlobalVariableT26.ncol/8)), dtype = np.int16)
    wAlphaContainer     = np.zeros((GlobalVariableT26.nrow, int(GlobalVariableT26.ncol/8)), dtype = np.int16)
    gPhiContainer       = np.zeros((GlobalVariableT26.nrow, int(GlobalVariableT26.ncol/8)), dtype = np.int16)
    gAlphaContainer     = np.zeros((GlobalVariableT26.nrow, int(GlobalVariableT26.ncol/8)), dtype = np.int16)
    bPhiContainer       = np.zeros((GlobalVariableT26.nrow, int(GlobalVariableT26.ncol/8)), dtype = np.int16)
    bAlphaContainer     = np.zeros((GlobalVariableT26.nrow, int(GlobalVariableT26.ncol/8)), dtype = np.int16)
    # OLED Stress Data Buffer Memory (for Transfer)
    rOSContainer        = np.zeros((GlobalVariableT26.nrow, int(GlobalVariableT26.ncol/8)), dtype = np.int64)
    wOSContainer        = np.zeros((GlobalVariableT26.nrow, int(GlobalVariableT26.ncol/8)), dtype = np.int64)
    gOSContainer        = np.zeros((GlobalVariableT26.nrow, int(GlobalVariableT26.ncol/8)), dtype = np.int64)
    bOSContainer        = np.zeros((GlobalVariableT26.nrow, int(GlobalVariableT26.ncol/8)), dtype = np.int64)
    # OLED Compensation Data Buffer Memory (for Transfer)
    rOCContainer        = np.zeros((GlobalVariableT26.nrow, int(GlobalVariableT26.ncol/8)), dtype = np.int16)
    wOCContainer        = np.zeros((GlobalVariableT26.nrow, int(GlobalVariableT26.ncol/8)), dtype = np.int16)
    gOCContainer        = np.zeros((GlobalVariableT26.nrow, int(GlobalVariableT26.ncol/8)), dtype = np.int16)
    bOCContainer        = np.zeros((GlobalVariableT26.nrow, int(GlobalVariableT26.ncol/8)), dtype = np.int16)
    # YCB Data Buffer Memory (for Transfer)
    rYCBContainer       = np.zeros((GlobalVariableT26.nrow, int(GlobalVariableT26.ncol/8)), dtype = np.int16)
    wYCBContainer       = np.zeros((GlobalVariableT26.nrow, int(GlobalVariableT26.ncol/8)), dtype = np.int16)
    gYCBContainer       = np.zeros((GlobalVariableT26.nrow, int(GlobalVariableT26.ncol/8)), dtype = np.int16)
    bYCBContainer       = np.zeros((GlobalVariableT26.nrow, int(GlobalVariableT26.ncol/8)), dtype = np.int16)
    # APG, GVC, CB, ATCB Data Buffer Memory (for Transfer)
    CBContainer         = np.zeros((GlobalVariableT26.CB_LINE, GlobalVariableT26.LINE_LENGTH), dtype = np.int16)
    APGContainer        = np.zeros((GlobalVariableT26.APG_LINE, GlobalVariableT26.LINE_LENGTH), dtype = np.int16)
    # Line Buffer (for Transfer)
    lut                 = [ np.zeros(GlobalVariableT26.LINE_LENGTH, dtype = np.int16), # 0
                            np.zeros(GlobalVariableT26.LINE_LENGTH, dtype = np.int16), # 1
                            np.zeros(GlobalVariableT26.LINE_LENGTH, dtype = np.int16), # 2
                            np.zeros(GlobalVariableT26.LINE_LENGTH, dtype = np.int16), # 3
                            np.zeros(GlobalVariableT26.LINE_LENGTH, dtype = np.int16), # 4
                            np.zeros(GlobalVariableT26.LINE_LENGTH, dtype = np.int16), # 5
                            np.zeros(GlobalVariableT26.LINE_LENGTH, dtype = np.int16), # 6
                            np.zeros(GlobalVariableT26.LINE_LENGTH, dtype = np.int16), # 7
                            np.zeros(GlobalVariableT26.LINE_LENGTH, dtype = np.int16), # 8
                            np.zeros(GlobalVariableT26.LINE_LENGTH, dtype = np.int16), # 9
                            np.zeros(GlobalVariableT26.LINE_LENGTH, dtype = np.int16), # 10
                            np.zeros(GlobalVariableT26.LINE_LENGTH, dtype = np.int16), # 11
                            np.zeros(GlobalVariableT26.LINE_LENGTH, dtype = np.int16), # 12
                            np.zeros(GlobalVariableT26.LINE_LENGTH, dtype = np.int16), # 13
                            np.zeros(GlobalVariableT26.LINE_LENGTH, dtype = np.int16), # 14
                            np.zeros(GlobalVariableT26.LINE_LENGTH, dtype = np.int16), # 15
                            np.zeros(GlobalVariableT26.LINE_LENGTH, dtype = np.int16), # 16
                            np.zeros(GlobalVariableT26.LINE_LENGTH, dtype = np.int16)] # 17
    lineBuffer          = np.zeros((4, GlobalVariableT26.LINE_LENGTH), dtype = np.int16)
    vParam              = np.zeros(GlobalVariableT26.LINE_LENGTH, dtype = np.int16)
    oParam              = np.zeros(GlobalVariableT26.LINE_LENGTH, dtype = np.int16)
    i2cByteBuffer       = 0
    commonVariable      = {}    
